### ISSUE TITLE
Not a( ¬a) won't display if an 'is' precedes it

### ISSUE THREAD

**Issue by joereynolds** [ehamberg/vim-cute-python#23]
I'm on Python 3.5 and The following statement doesn't work correctly

```
  if self.buffer[self.buffer_end] is not None: 
      self.buffer_start += 1
```

However, the following (notice the lack of 'is') does work (but obviously is syntactically wrong)
```
   if self.buffer[self.buffer_end] not None:   
       self.buffer_start += 1
```

**Comment by joereynolds** [comment]
Just read the comment on the file.

```
" include the space after “not” – if present – so that “not a” becomes “¬a”.
" also, don't hide “not” behind  ‘¬’ if it is after “is ”.
```

So it's not a bug but is there any reason for this behaviour?

**Comment by ehamberg** [comment]
Yeah, that's intentional. :)

`is not` is a completely different operator from `not`. The `is not` and its dual `is` is for testin whether two objects are the same, while `not` is a logical operator that negates what follows and it therefore makes sense to use the negation symbol in that case.

For `is not` and `is`, some equivalence operator and its opposite would be more appropriate, but the words *is* and *is not* already work quite well. :)
